// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderlistMw() []app.HandlerFunc {
	// your code...
	// res := []app.HandlerFunc{
	// 	middleware.JwtMiddleware.MiddlewareFunc(),
	// }
	// return res
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}
