// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadimagesMw() []app.HandlerFunc {
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _prodcutpagenumMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadImagesMw() []app.HandlerFunc {
	return nil
}
