// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	admin "github.com/wuyuesong/douyinmall/app/gateway/biz/router/admin"
	auth "github.com/wuyuesong/douyinmall/app/gateway/biz/router/auth"
	cart "github.com/wuyuesong/douyinmall/app/gateway/biz/router/cart"
	category "github.com/wuyuesong/douyinmall/app/gateway/biz/router/category"
	checkout "github.com/wuyuesong/douyinmall/app/gateway/biz/router/checkout"
	home "github.com/wuyuesong/douyinmall/app/gateway/biz/router/home"
	image "github.com/wuyuesong/douyinmall/app/gateway/biz/router/image"
	order "github.com/wuyuesong/douyinmall/app/gateway/biz/router/order"
	payment "github.com/wuyuesong/douyinmall/app/gateway/biz/router/payment"
	product "github.com/wuyuesong/douyinmall/app/gateway/biz/router/product"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	payment.Register(r)

	image.Register(r)

	admin.Register(r)

	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	auth.Register(r)

	category.Register(r)

	product.Register(r)

	home.Register(r)
}
