// Code generated by hertz generator.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homeMw() []app.HandlerFunc {
	// your code...
	return nil
}
