// Code generated by hertz generator.

package image

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _imageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _image0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
