// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}
