// Code generated by hertz generator.

package cart

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/wuyuesong/douyinmall/app/gateway/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JwtMiddleware.MiddlewareFunc()}
}

func _addcartitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcartMw() []app.HandlerFunc {
	// your code...
	return nil
}
